// Generated by https://quicktype.io

export interface PostProps {
  userId: number;
  id: number;
  title: string;
  body: string;
}

// Generated by https://quicktype.io

export interface CommentProps {
  postId: number;
  id: number;
  name: string;
  email: string;
  body: string;
}
